import React, { useState } from "react";
import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import fetchRequests from "../utils/requests";
import MovieCard from "../components/MovieCard";

export default function Home({ results }) {
  //states
  const [movieInfo, setMovieInfo] = useState("");
  const [showMovieInfo, setShowMovieInfo] = useState(false);
  //controla oq será exibido no modal
  const movieInfoHandler = (movieData, handlerData) => {
    setMovieInfo(movieData);
    setShowMovieInfo(handlerData);
  };
  //close card function
  const closeCardHandler = (data) => {
    setShowMovieInfo(data); //'state' vem de <MovieCard/>
  };
  console.log(results);
  return (
    <div>
      <Head>
        <title>Hulu Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/*HEADER*/}
      <Header />

      {/* NAV*/}
      <Nav />

      {/* RESULTS */}
      <Results results={results} onGetMovieInfo={movieInfoHandler} />
      {showMovieInfo && (
        <MovieCard selectedMovie={movieInfo} onChangeState={closeCardHandler} />
      )}

      <Footer />
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const request = await fetch(
    `https://api.themoviedb.org/3${
      fetchRequests[genre]?.url || fetchRequests.fetchTrending.url
    }`
  ).then((result) => result.json());

  return {
    props: {
      results: request.results,
    },
  };
}
